### ISSUE TITLE
ログイン機能 Issue1 メールアドレス／パスワードでログイン出来る

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team2D#7]
## 終了条件

メールアドレス／パスワードを入力し、ログインボタン押すとログイン出来る
入力されたメールアドレス／パスワードをもとにDB検索、入力情報が正しいかチェックする
正しい場合はセッション情報を作成し、トップページに移動する
正しくない場合は、その旨画面にメッセージを表示する
トップページにアクセス時に未ログインの場合はログイン画面に遷移する
※サンプルのログイン画面に用意してある、ログイン状態を保持するの文言とチェックボックスは削除する

## 備考

ユーザレコードはSQLで作成
ログイン画面は用意してある

**Comment by Yuta0227** [comment]
## 関連イシュー
特になし

## 検証したこと
メールアドレス／パスワードを入力し、ログインボタン押すとログイン出来る
入力されたメールアドレス／パスワードをもとにDB検索、入力情報が正しいかチェックする
正しい場合はセッション情報を作成し、トップページに移動する
正しくない場合は、その旨画面にメッセージを表示する
トップページにアクセス時に未ログインの場合はログイン画面に遷移する
※サンプルのログイン画面に用意してある、ログイン状態を保持するの文言とチェックボックスは削除する

## エビデンス
ログイン画面（ログインせずにhttp://localhost:8080/index.phpにアクセスするとリダイレクトされる）
![image](https://user-images.githubusercontent.com/86890087/188780138-1df6d9d3-d176-4a24-8f3e-9a3145a4bc60.png)
ログインに失敗
![image](https://user-images.githubusercontent.com/86890087/188780322-6b6d2922-8463-4e1d-9435-18fed812bc30.png)
ログインに成功
![image](https://user-images.githubusercontent.com/86890087/188780235-6c7dd5a1-6829-444f-b0e3-dad583d2f4aa.png)

## 備考
簡単のため、ログアウト機能を実装した
